### ISSUE TITLE
[CombatControlsRedux] EN translation review + DE (new)

### ISSUE THREAD

**Issue by NightFright2k19** [NormanPCN/StardewValleyMods#2]
EN (default.json):
Rephrased options for easier understanding and fixed some typos.

DE (de.json): 
All-new translation done by myself.

[translation.zip](https://github.com/NormanPCN/StardewValleyMods/files/9036524/translation.zip)

**Comment by NormanPCN** [comment]
Thanks for the fixes and translation. I'll incorporate these shortly in v1.2.4.
